services:
  infrastructure:
    path: services/infrastructure
    dependsOn: []
  
  webhook-service:
    path: services/webhook-service
    dependsOn:
      - infrastructure
  
  inbound-message-processor:
    path: services/inbound-message-processor
    dependsOn:
      - infrastructure
  
  outbound-message-processor:
    path: services/outbound-message-processor
    dependsOn:
      - infrastructure

  websocket-service:
    path: services/websocket-service
    dependsOn:
      - infrastructure

config:
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
