service: omnichannel-inbound-message-processor

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  
  environment:
    STAGE: ${self:provider.stage}
    AURORA_CLUSTER_ARN: ${cf:omnichannel-infrastructure-${self:provider.stage}.AuroraClusterArn}
    AURORA_SECRET_ARN: ${env:AURORA_SECRET_ARN}
    AURORA_DATABASE: omnichannel
    WEBSOCKET_API_ID: ${cf:omnichannel-infrastructure-${self:provider.stage}.WebSocketApiGatewayId}
  
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - rds-data:ExecuteStatement
            - rds-data:BatchExecuteStatement
          Resource: ${cf:omnichannel-infrastructure-${self:provider.stage}.AuroraClusterArn}
        - Effect: Allow
          Action:
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
          Resource: ${cf:omnichannel-infrastructure-${self:provider.stage}.MessageQueueArn}
        - Effect: Allow
          Action:
            - execute-api:ManageConnections
          Resource: 
            - arn:aws:execute-api:${self:provider.region}:*:${cf:omnichannel-infrastructure-${self:provider.stage}.WebSocketApiGatewayId}/*/*

functions:
  messageProcessor:
    handler: handler.messageProcessor
    timeout: 60
    events:
      - sqs:
          arn: ${cf:omnichannel-infrastructure-${self:provider.stage}.MessageQueueArn}
          batchSize: 10

plugins:
  - serverless-webpack

webpack:
  webpackConfig: 'webpack.config.js'
  includeModules: true
